// ============================================================
// PRISM — Markdown Export Utility
// ============================================================

import type { PrismResult } from './types';

export function generateMarkdownReport(result: PrismResult): string {
    const { input, phase1, phase2, phase3, phase4 } = result;

    return `# 【WE型】超高速・社会言語開発レポート：PRISM

> **対象:** ${input.productName}（${input.category}）
> **生成日:** ${new Date().toLocaleDateString('ja-JP')}

---

## 1. Deep Listening：前提の整理

### 生活者の生の声 (Positive / Hack)

${phase1.positiveHacks.map((h) => `- ${h}`).join('\n')}

### 生活者の生の声 (Negative / Pain)

${phase1.negativePains.map((p) => `- ${p}`).join('\n')}

### 市場の再定義

> ${phase1.marketRedefinition}

---

## 2. Core Ideas：3つの社会言語案

| 社会言語（案） | 販促ストーリー | 根拠・ファクト |
| :--- | :--- | :--- |
${phase2
            .map(
                (sl) =>
                    `| **${sl.keyword}** | ${sl.story.replace(/\n/g, ' ')} | ${sl.fact.replace(/\n/g, ' ')} |`
            )
            .join('\n')}

---

## 3. Survey Design：イシューデザイン調査

### 定量設問

${phase3.quantitative.map((q, i) => `${i + 1}. ${q}`).join('\n')}

### 定性設問

${phase3.qualitative.map((q, i) => `${i + 1}. ${q}`).join('\n')}

---

## 4. Conclusion：ポジショニング提案

### 提言

${phase4.positioning}

### ニュース見出し案

> ${phase4.newsHeadline}

---

## 調査レポートサマリ

${phase4.reportSummary}

---

## プレスリリース

${phase4.pressRelease}

---

*Generated by PRISM — Public Resonance & Insight Synthesis Module*
*Powered by Antigravity*
`;
}
